### ISSUE TITLE
edit that in https://github.com/Wurst-Imperium/Wurst7/pull/526

### ISSUE THREAD

**Issue by xVirum** [KTibow/KTibow#1]
"description.wurst.hack.clickaura": "Автоматично атакує найближчу сутність, коли ви натискаєте ЛКМ.\n\n§c§lУВАГА:§r ClickAura'и звичайно виглядають більш підозріло, ніж Killaura'и і легше виявляються плагінами. Краще використовувати Killaura або TriggerBot.",

line 42 plz

**Comment by KTibow** [comment]
Added.

**Comment by xVirum** [comment]
<3
