### ISSUE TITLE
NER

### ISSUE THREAD

**Issue by deceased1** [KTibow/KTibow#2]
when you left an issue with NER did it actually have an ssid stealer?

**Comment by KTibow** [comment]
send a link to the issue

**Comment by deceased1** [comment]
> send a link to the issue

https://github.com/NotEnoughRacism/NotEnoughRacism/issues/1

**Comment by KTibow** [comment]
nah i was just dumb back then and didn't know how you could create a server join cred, which proves you are you without sending your session id
