### ISSUE TITLE
Comment on my blog?

### ISSUE THREAD

**Issue by purplesyringa** [KTibow/KTibow#3]
GitHub sent me a notification from you on https://github.com/purplesyringa/site/commit/1713ca2f6c1c5eb82bc6f796183f984fefcf14c4 but I can't find any comment there. I'm wondering if you wanted to tell me something or it was accidental?

**Comment by KTibow** [comment]
Ah, I was mentioning that there should be a space between `DOCTYPE` and `html`. Admittedly it was a bit pedantic, but some other people were talking about it and I wanted to know if that was an intentional or unintentional choice.

**Comment by purplesyringa** [comment]
Ah. That's intentional. I'm using an HTML minifier that removes absolutely everything unnecessary (ridiculous, I know). I've yet to see this breaking any browser.
